import React from 'react';
import {
  LayoutDashboard,
  Users,
  BarChart3,
  Settings,
  Bell,
  Search,
  Filter,
  MoreVertical,
  Check,
  X,
  RotateCcw,
  Trash2,
  Calendar,
  Briefcase,
  DollarSign,
  ChevronRight,
  ChevronDown,
  ArrowUpRight,
  Download,
  Menu,
  MessageSquare,
  Eye,
  ShieldCheck,
  CheckCircle2,
  Upload,
  Clock,
  Activity,
  MapPin,
  Ticket,
  Mail,
  Phone,
  CreditCard,
  AlertTriangle,
  FileText,
  FileX,
  ImageOff,
  Loader2,
} from 'lucide-react';

export const Icons = {
  Mail: Mail,
  Phone: Phone,
  Ticket: Ticket,
  Upload: Upload,
  Clock: Clock,
  Activity: Activity,
  MapPin: MapPin,
  Dashboard: LayoutDashboard,
  Users: Users,
  Analytics: BarChart3,
  Settings: Settings,
  Bell: Bell,
  Search: Search,
  Filter: Filter,
  More: MoreVertical,
  Check: Check,
  Reject: X,
  Undo: RotateCcw,
  Delete: Trash2,
  Calendar: Calendar,
  Briefcase: Briefcase,
  Dollar: DollarSign,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  TrendUp: ArrowUpRight,
  Download: Download,
  Menu: Menu,
  Chat: MessageSquare,
  Eye: Eye,
  ShieldCheck: ShieldCheck,
  CheckCircle2: CheckCircle2,
  CreditCard: CreditCard,
  AlertTriangle: AlertTriangle,
  FileText: FileText,
  FileX: FileX,
  ImageOff: ImageOff,
  Spinner: Loader2,
};